name: Build qjsc.wasm Builder image and WASM Binary using Docker

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  esbuildwasmbuild:
    runs-on: golang

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker container
        run: docker build --tag esbuild-wasi

      - name: Run Docker Container to build esbuild
        run: mkdir -p ${{ github.workspace }}/build && touch ${{ github.workspace }}/build/esbuild.wasm && docker run --rm --platform linux/amd64 -v ${{ github.workspace }}/build:/build esbuild-wasi

      - name: Upload artifact compiler, esbuild.wasm
        uses: actions/upload-artifact@v4
        with:
          name: esbuild.wasm
          path: /build/esbuild.wasm
